version: '3'

services: 
    apidev:
        container_name: dev
        build: 
            context: .
            dockerfile: dockerfile.dev
        volumes: 
            - .:/volumes/dev
        environment: 
            PORT: 3333
        ports:
            - 3333:3333
            - 9292:9292
 