version: '3'

services: 
    apidev:
        container_name: dev
        working_dir: /usr/src/api
        image: node:14.16.0-alpine
        command: sh -c "npm install --only=prod && npm run debug"
        volumes:
            - ./dist/:/usr/src/api/dist
            - ./package.json:/usr/src/api/package.json
        environment: 
            PORT: 3333
            URL: https://square-meter-value.herokuapp.com/
        ports:
            - 3333:3333
            - 9222:9222
 